"""Persistent summary nodes and generated story drafts, additive migration."""

import sqlalchemy as sa

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_drafts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("chapters", sa.JSON(), nullable=False),
        sa.Column("connections", sa.JSON(), nullable=False),
        sa.Column("node_versions", sa.JSON(), nullable=False),
        sa.Column("artifact_revision", sa.Integer(), nullable=False),
        sa.Column("agent_revision", sa.Integer(), nullable=False),
        sa.Column("skill_name", sa.String(), nullable=False),
        sa.Column("skill_hash", sa.String(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(op.f("ix_story_drafts_project_id"), "story_drafts", ["project_id"], unique=False)
    op.create_table(
        "story_nodes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("source_message_id", sa.String(), nullable=False),
        sa.Column("source_reply_id", sa.String(), nullable=False),
        sa.Column("lane", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("next_step", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("include_in_story", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_reply_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_nodes_project_id"), "story_nodes", ["project_id"], unique=False)
    op.create_index(op.f("ix_story_nodes_run_id"), "story_nodes", ["run_id"], unique=False)
    op.create_table(
        "node_revisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["story_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "version"),
    )
    op.create_index(op.f("ix_node_revisions_node_id"), "node_revisions", ["node_id"], unique=False)
    op.add_column("projects", sa.Column("agent_revision", sa.Integer(), server_default="0", nullable=False))
    op.add_column("runs", sa.Column("task_kind", sa.String(), server_default="guide", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Restore a verified backup; do not delete story nodes implicitly.")
