import { expect, test } from "@playwright/test";

test("create, discuss, adopt, edit, history, withdraw, restore and export", async ({ page }, info) => {
  await page.goto("/");
  await expect(page.getByText("模拟体验", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "开始我的故事" }).click();
  await page.getByLabel("故事名称").fill(`渡口来信-${Date.now()}`);
  await page.getByRole("button", { name: "建立故事" }).click();
  await page.getByRole("button", { name: "还没方向，给我一点启发" }).click();
  await expect(page.getByRole("heading", { name: "一封不该送到的信" })).toBeVisible();
  await page.getByLabel("你的想法").fill("都挺好");
  await page.getByRole("button", { name: "发送想法" }).click();
  await expect(page.getByText("这些方向先保留为待讨论，没有采用任何设定。")).toBeVisible();
  await page.getByLabel("你的想法").fill("用第二个");
  await page.getByRole("button", { name: "发送想法" }).click();
  await expect(page.getByText("已采用「最后一个守桥人」", { exact: false })).toBeVisible();
  if (info.project.name === "mobile") await page.getByRole("button", { name: "故事资料 · 1" }).click();
  await expect(page.locator(".note-card")).toHaveCount(1);
  await page.getByRole("button", { name: "编辑", exact: true }).click();
  await page.getByLabel("内容", { exact: true }).fill("守桥人是一名失去记忆的剑客。");
  await page.getByRole("button", { name: "保存设定" }).click();
  await expect(page.locator(".note-card")).toContainText("失去记忆");
  await page.getByRole("button", { name: "历史", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("版本 1");
  await expect(page.getByRole("dialog")).toContainText("版本 2");
  await page.getByRole("button", { name: "关闭历史" }).click();
  await page.reload();
  if (info.project.name === "mobile") await page.getByRole("button", { name: "故事资料 · 1" }).click();
  await expect(page.locator(".note-card")).toContainText("失去记忆");
  await page.getByRole("button", { name: "撤回", exact: true }).click();
  await expect(page.locator(".note-card")).toHaveCount(0);
  await page.locator(".withdrawn summary").click();
  await page.getByRole("button", { name: "恢复", exact: true }).click();
  await expect(page.locator(".note-card")).toHaveCount(1);
  const downloadPromise = page.waitForEvent("download");
  await page.locator(".export-button").click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("story-notes.md");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/${info.project.name}-workspace.png`, fullPage: true });
});

test("direct note is reversible and unsent draft survives refresh", async ({ page }, info) => {
  await page.goto("/");
  await page.getByRole("button", { name: "开始我的故事" }).click();
  await page.getByLabel("故事名称").fill(`孤舟-${Date.now()}`);
  await page.getByRole("button", { name: "建立故事" }).click();
  await page.getByLabel("你的想法").fill("还没发送的灵感");
  await page.reload();
  await expect(page.getByLabel("你的想法")).toHaveValue("还没发送的灵感");
  if (info.project.name === "mobile") await page.getByRole("button", { name: "故事资料 · 0" }).click();
  await page.getByRole("button", { name: "添加设定" }).click();
  await page.getByLabel("标题", { exact: true }).fill("渡口");
  await page.getByLabel("内容", { exact: true }).fill("故事发生在一个常年落雨的渡口。");
  await page.getByRole("button", { name: "保存设定" }).click();
  await expect(page.locator(".note-card")).toContainText("常年落雨");
  await page.getByRole("button", { name: "撤回", exact: true }).click();
  await expect(page.locator(".note-card")).toHaveCount(0);
});
